language: python

python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install coverage
  - pip install --upgrade setuptools

install:
  - pip install -r requirements.txt

script:
   "coverage run -m unittest discover -s . -p 'test_*.py'"

after_success:
  "coverage report" # submit coverage


